// midi/MotifPatches.cpp — Yamaha MOTIF-RACK Normal Voice name table (AITEC 2026-07-12)
// Fuente verificada: docs/Yamaha_MOTIF-RACK_Normal_Voice_List.md
//   - MOTIFRACKE2.pdf (Data List oficial Yamaha, páginas 2-9), pdftotext -layout.
// Solo Normal Voice (8 bancos x 128 = 1024). Sin Drum Voice ni Multi (no
// verificados en el documento fuente). User2 es copia de fábrica de Preset5.
#include "MotifPatches.h"

static const char* const kPreset1[128] = {
    "PowerGrand",     "Jazz Grand",     "Dark Grand",     "CP 80",
    "CP80&EP",        "Yama EP's",      "BalladKeys",     "80s Layer",
    "Piano&Strg",     "Piano Ooh",      "PianoBakup",     "Max Tine",
    "Early Fusn",     "Vintage'74",     "Sweetness",      "DynoStrait",
    "ChorusHard",     "VintagCase",     "ChorusDyno",     "80th Boost",
    "Contempo",       "Early 70's",     "Tonight",        "E.PianoPad",
    "TX802",          "ChorusBel",      "BellDX",         "Dark DX",
    "GS Tines",       "Rich FM",        "FilteredDX",     "Ice Piano",
    "WurliTrem",      "WurliAmped",     "TouchClavi",     "SuperClavi",
    "StereoClav",     "HollowClav",     "Nu Phasing",     "Digi Clavi",
    "PulseClavi",     "Twinkle",        "Stick Bell",     "Bell Chiff",
    "FngrCymbl",      "ChorusBell",     "Tibetan",        "EastBell",
    "Gamelan",        "IceBells",       "Digi Bell",      "Marimbell",
    "16+8+5&1/3",     "Petit",          "Glassy",         "Jazzy",
    "Slow Jam",       "Greasy",         "Swishie",        "Clean",
    "Full/CVib",      "Mellow",         "Nu Shade",       "Cool Cat",
    "Flutey",         "LeftManual",     "DrawContrl",     "Rocky",
    "Expensive",      "Progressy",      "Crunchy",        "Early Bird",
    "Jazz Split",     "GosplSplit",     "Tradi",          "Sunday",
    "BreathPipe",     "Fluty Pipe",     "Reedy Pipe",     "OohPipes",
    "Flamenco",       "Nylon Jam",      "BriteSteel",     "Strums",
    "Big Steel",      "Folk Steel",     "18 String",      "HarpsiGtr",
    "HybridGtr",      "JazzGTmelo",     "Velo Jazz",      "FM Jazz",
    "For Funk",       "Spanky",         "Funkiest",       "Vin Strum",
    "1CoilChors",     "CleanChors",     "ChorusPlus",     "SmoothChor",
    "TexBoogie",      "Rockabilly",     "65 Combo",       "VinTremolo",
    "Crunchoid",      "DynamicAmp",     "Feedback",       "VOODOOMAN",
    "BlueLead",       "MeloRckLd",      "MetalMute",      "OverTheTop",
    "RoundWound",     "FingerMan",      "PrecRW",         "PrecFW",
    "HybridBass",     "Stand Up",       "Fretless",       "Slap&Fx",
    "BriteSlap",      "Velo Bass",      "Bs+Cym+Vb",      "Boogie on",
    "MiniDetune",     "Long Spit",      "Tack Bass",      "Fat Octave",
};

static const char* const kPreset2[128] = {
    "Violin",         "Viola",          "Cello",          "SoloSpicat",
    "2 Solos",        "Cello Duet",     "Trio",           "Chamber",
    "Small Ens",      "Medium Ens",     "Ens Mix",        "Ensemble",
    "Hard Ens",       "Background",     "BigSymphny",     "Str/Horns",
    "Stringy",        "Polystring",     "JP Strings",     "MournStrgs",
    "The Pizz",       "Fanfare",        "Hi Brass",       "Fat Sect",
    "Sforzando",      "Symphony",       "Big Band",       "Big Band 2",
    "SaxBigBand",     "MedmBrass",      "Soft Brass",     "SoftVeloBr",
    "TrpRomantc",     "Phase Mute",     "Legend",         "Trombone",
    "Flugelleaz",     "F.Horn Ens",     "SlowAttack",     "Strng/Bras",
    "Movie Ens",      "Powered",        "ObStuff",        "Prophy",
    "AnalogBras",     "After 1984",     "Soprano",        "Alto Vib",
    "SaxEnsembl",     "Tenor Sax",      "Tenor Soft",     "The Winds",
    "WindOrch",       "SweetFlute",     "PanBottle",      "AmpHarpMW",
    "SmoothSaw",      "Lucky",          "Tri Solo",       "Syntrump",
    "PWM Lead",       "Clicky Saw",     "Mini Pulse",     "Sync Lead",
    "Altair",         "Analog",         "Sweetland",      "WarmSweepy",
    "SinePad",        "Square",         "VoxPad",         "Pure Syn",
    "MovingPad",      "SimpleSaws",     "X-Shower",       "PWM Pad",
    "Bell Choir",     "ObSoft",         "MellowAnlg",     "Glasschoir",
    "PeaceVox",       "StackChoir",     "Bronx",          "IceChoir",
    "Fast Oohs",      "Ooze & OZ",      "NeoCrystal",     "Pop Synth",
    "Fantasy",        "Heavenly",       "Retro",          "Airy Nylon",
    "Antares",        "Pan Sphere",     "Tamburax",       "IndianFlai",
    "SAKURA",         "RisingHigh",     "Champ",          "Gladiator",
    "Hades",          "Glacy",          "Forest",         "MirrorRing",
    "Poly",           "AnaTonk",        "Jaipur",         "Dulcitar",
    "Cimbalon",       "EthncFlute",     "Hichiriki",      "Ryuteki",
    "Gagaku",         "Kokyu",          "Digidoo",        "Bali",
    "Indo",           "Trip East",      "Tabla",          "Djembe",
    "Djerimbe",       "Udu",            "Tribal",         "Log&Drum",
    "Afro",           "Japanesque",     "EthnoShock",     "Ethnology",
};

static const char* const kPreset3[128] = {
    "Wide Comp",      "78rpmPiano",     "Bristol",        "Mono Comp",
    "Dance",          "Houze",          "Glass EP",       "VintSwitch",
    "Early Case",     "RdsScape",       "RichEcho",       "StringyPno",
    "Champagne",      "Moet",           "Compact",        "1967 Keys",
    "YD-45C",         "Gnarly",         "Modular",        "Dark Jack",
    "OneVoice",       "Dry Syn",        "PlasticBas",     "Bassline",
    "RubbaRap",       "Juicy",          "Dark",           "UniBass",
    "Flyer",          "QuackBass",      "Moonbass",       "ClassicSub",
    "DX100",          "Lately",         "FMBass",         "Oct String",
    "3 Octave",       "TapeStrngs",     "VP Strings",     "BriteTeeth",
    "XDance",         "Timeless",       "FatSynth",       "Big Syn",
    "Bluesharp",      "Sync",           "Atk Reso",       "Singleline",
    "Free LFO",       "Soft Lead",      "PulseWound",     "Big Drone",
    "Big Tune",       "PowerWheel",     "Flangefilt",     "G-Funk",
    "Maria AT",       "InThePast",      "FatSawPad",      "Wide Sweep",
    "Sunbeams",       "BPFx",           "FrozenPad",      "MICHINOKU",
    "Esmeralda",      "Romance",        "Circle",         "Dreamspher",
    "Silverlake",     "Shadow",         "Platinum",       "Gently",
    "Warming",        "PW-EMMY",        "X-fade Pad",     "Zosma",
    "NoizRezz",       "Mira",           "MultiPulse",     "VoxWaves",
    "LazySweep",      "Doomed",         "PerkaVox",       "Punchy",
    "Eyeliner",       "Quieck",         "Aladdin",        "QuadSwell",
    "Lilley Pad",     "Didje Baz",      "RING PAD",       "Chaser 1",
    "Chaser 2",       "Spacebreat",     "Long HiPa",      "Action Y",
    "Trancelan",      "Eternal",        "VirtualSyn",     "Interlude",
    "Flying",         "TheSlayer",      "White Rabb",     "Siam",
    "Ududu",          "Particle",       "Shaper",         "VintageArp",
    "Aah Dance",      "Joker",          "Holiday",        "Android",
    "Spacious",       "VoiceCuica",     "Pop Arp",        "Ping Pong",
    "Amoeba",         "Landing",        "I was born",     "PsychoGtr",
    "NoGravity",      "Pulser",         "Racer",          "Storm",
    "Oscillatin",     "FamlyFeud",      "WatrForest",     "Spacecraft",
};

static const char* const kPreset4[128] = {
    "MultcmpPno",     "Light",          "ConcrtGrnd",     "Balld Stck",
    "Hard CP80",       "StereoComp",    "MetalPiano",     "Old Piano",
    "Diablo",         "Satellite",      "SummerTime",     "SparkleTin",
    "Tine E",         "Mr. Klank",      "DX7+Pad",        "PluckBells",
    "RetroWurli",     "DampedClav",     "Dummy",          "Neo Soul",
    "EpfCrusher",     "PlukdThing",     "Hiss Pad",       "GlassBells",
    "YumiBell",       "Pad Bells",      "EthnoStone",     "BellsAbuzz",
    "Icey Vibe",      "Gongladeer",     "ScaryNight",     "MoreDrwbrs",
    "Soulemn",        "Green",          "JimyPercC3",     "Dirt Organ",
    "Vint Drive",     "Yoshi Perc",     "Big Track",      "Circus",
    "Mikuni'sFI",     "Elemental",      "Farfasso",       "Willis",
    "Reed",           "Partita",        "Policia",        "Jazzmaster",
    "Trip Rotor",     "Radio Cmp2",     "Simple WAH",     "Wah-Riff",
    "Guitar&Pad",     "Coral",          "Harp",           "RnB Harp",
    "Precsn Cmp",     "TubeFinger",     "Finger Amp",     "It'sRounda",
    "NoResBass",      "Fat Sine",       "Wobble",         "Decor",
    "Thump",          "EmFunk",         "FatOctaRes",     "Org Bass",
    "FM Klick",       "Fat Low",        "SimplePowr",     "VeloString",
    "NoSofia St",     "HoodStrngs",     "FullStrngs",     "Chamber AT",
    "Big Swell2",     "BlueString",     "Old String",     "78rpmStrgs",
    "Ens+Flute",      "Bells&Bows",     "The Pad",        "Full PWM",
    "HybridSect",     "TaniBrass",      "Hybrid",         "F HornSec2",
    "Hi Brass 2",     "Brassy",         "Hybri Pad",      "Oberhorns",
    "PiccoloTpt",     "Flugelist",      "Soprano 3",      "4Brothers",
    "Antique",        "Flutter Fl",     "Real Flute",     "Querfloete",
    "Oboe+EHorn",     "FluteChord",     "Mini Soft",      "Portatone",
    "Sine Ld 2",      "Bare Saw",       "Green Eyes",     "inda Night",
    "Shine on",       "Simp. Pad",      "Voxxaire",       "Angelvoice",
    "Shangralo",      "Warm PWM",       "Balcony",        "Alabaster",
    "BackPad MW",     "Dark Tower",     "Basic Poly",     "Straight",
    "Soleil",         "Ana Synth1",     "PopularSyn",     "For Bertje",
    "Udu Too",        "Funky Mood",     "Step Down",      "Shantasma",
};

static const char* const kPreset5[128] = {
    "Gruvmaster",     "ANbasicARP",     "Europa",         "Q Machine",
    "Happy Boy",      "X-Pulsar",       "Tekno Spy",      "Tuff Arp",
    "Polygroove",     "OrangeMW",       "Hip Chordz",     "Em Arp",
    "LostIsland",     "Bobby Bass",     "RnBass",         "SimpleBss2",
    "SimpleReso",     "BobbyJuice",     "Bass&Comp!",     "TranceBass",
    "Emlate",         "Velomaster",     "Kick Bass",      "Hollow",
    "Em Bass",        "Oxide",          "Acidd",          "Pirate",
    "AgressoFx",      "LOFI-BASS",      "Quack",          "ConeFlappe",
    "Warmest",        "FatStrings",     "Superstrgs",     "JupiterStr",
    "MIDIPAD",        "AKIRABRASS",     "TV Brass",       "Oberbrass",
    "Thinth",         "Trendy",         "Tech Lead",      "PulseWidth",
    "Mr. Finger",     "Punch Lead",     "GOA LEAD",       "I.C.U.2.",
    "Space Lead",     "Lead Wait",      "Pig Lead",       "Chordz",
    "Twilight",       "VDU Pad",        "HPF+LPFpad",     "Sonar Pad",
    "Whisperer",      "Flangerous",     "Sadness",        "Super Back",
    "Bastille",       "Fat Swell",      "Pad&Syn",        "Eurostar",
    "Pretty far",     "Needles",        "VectorPad1",     "Wake Up",
    "Ether",          "Spiralised",     "RezSinePad",     "Granular",
    "Ropey",          "Smear",          "Mizar",          "Homesick",
    "Lost.",          "Haunting",       "Infant",         "High Sine",
    "Sm.OrganPd",     "Chianti",        "Guitar Pad",     "Tuscan",
    "Shuttle",        "Ether 2",        "Sine Comp",      "Queens",
    "Kairo",          "Synes XL",       "FaaatDance",     "Random LFO",
    "Vacuum",         "RezzPunch",      "Kordal MW",      "M-Trance",
    "Euro",           "DX Metal",       "Atlantis",       "Meteors",
    "Girlfriend",     "Nebula AT",      "CosmicRain",     "Contact",
    "Dalahi",         "CrushpadMW",     "Ar-tic",         "Alaska",
    "Clusters",       "Glister",        "SliceIt Up",     "Chaser 3",
    "Surface",        "Stalagtite",     "4ling Star",     "Old Skool",
    "Katsu",          "Genie",          "Dream Text",     "Ambi Rain",
    "Bitzz MW",       "JumpQ MW",       "Molt",           "Samsara",
    "FX-MWSweep",     "Static",         "Wriggle",        "Kraftbeat",
};

// GM (msb=0x00 lsb=0x00) — igual set de nombres que kPreset5 (fábrica).
static const char* const kGM[128] = {
    "NaturlGrnd",     "Rock Brite",     "CP 2001",        "Honkytonk",
    "E.Piano 1",      "E.Piano 2",      "Harpsicord",     "Brite Clav",
    "Celeste",        "Glocken",        "Music Box",      "Vibes",
    "Marimba",        "Xylophone",      "TublarBell",     "Dulcimar",
    "Draw Organ",     "Perc Organ",     "Rock Organ",     "ChurchOrgn",
    "Reed Organ",     "Accordion",      "Harmonica",      "TangoAccrd",
    "Nylon",          "Steel",          "ModernJazz",     "Clean",
    "Mute",           "Overdrive",      "Distortion",     "Harmonics",
    "Accoustic",      "FingerBass",     "Pick Bass",      "Fretless 2",
    "SimpleSlap",     "Velo Slap",      "SynthBass1",     "SynthBass2",
    "Violin 2",       "Viola 2",        "Cello 2",        "Contrabass",
    "TremoloStr",     "Pizz",           "Harp",           "Timpni+Cym",
    "StereoSt1",      "StereoSt2",      "Grand Saw",      "SynStrings",
    "Aah Choir",      "Ooh Choir",      "Syn Voice",      "Orch.Hit",
    "Trumpet",        "Trombone 2",     "Tuba",           "MuteTrpt 2",
    "F.Horns",        "Brass Sect",     "SynthBrass",     "Soft Brass",
    "Soprano 2",      "Alto Sax",       "TenorSax 2",     "Bari Sax",
    "Oboe",           "Eng.Horn",       "Bassoon",        "Clarinet",
    "Piccolo",        "Flute",          "Recorder",       "Panflute",
    "Bottle",         "Shakuhachi",     "Whistle",        "Ocarina",
    "Square Ld",      "Saw Ld",         "Caliop Ld",      "Chiff Ld",
    "Charan Ld",      "Voice Ld",       "Fifth Ld",       "Bass&Ld",
    "New Age",        "Warm Pad",       "Poly Synth",     "Choir Pad",
    "BowedPad",       "Metal Pad",      "Halo Pad",       "Sweep Pad",
    "Rain Pad",       "SoundTrack",     "Crystal",        "Atmosphere",
    "Brightness",     "Goblin",         "Echoes",         "Sci-Fi",
    "Sitar",          "Banjo",          "Shamisen",       "Koto",
    "Kalimba",        "Bagpipe",        "Fiddle",         "Shanai",
    "Tinkerbel",      "Agogo",          "Steeldrum",      "Woodblock",
    "Taikodrum",      "MelodicTom",     "Synth Drum",     "Rev Cymbal",
    "Fret Noise",     "BreathNoiz",     "Seashore",       "Tweet",
    "Telephone",      "Helicopter",     "Applause",       "Gunshot",
};

static const char* const kUser1[128] = {
    "M25 M.W.",       "Softstars",      "Fast PWM",       "Terminator",
    "Soft Tar",       "Sorted",         "Trendy Wah",     "Feed S&H",
    "Didge",          "Old House",      "HPF Dance",      "Like Bees",
    "Exodus",         "S/H Gruv",       "Funk It!!",      "Opening",
    "DigDag",         "Dark Light",     "Boom Bass",      "Dirtbox",
    "Shandala",       "Titan",          "Puls Step",      "Racket",
    "Big Lead",       "Blush",          "Squeaky",        "Duck Worm",
    "Jon",            "Weird scar",     "Auto Wah",       "MINIMAL",
    "MGul",           "BrokenStar",     "Smooth",         "Sawmill",
    "Cavern",         "Supersnap",      "Fuzzline",       "Foreplay",
    "Brooklyn",       "Brief",          "Dist-MW",        "Hit&Down",
    "Froglegs",       "Sand",           "R&B Steel",      "Rabbit",
    "ElecWorld",      "Sickday",        "LoSnake",        "Boomeran",
    "O+Ca+Si+Na",     "Space Run",      "Additive",       "Rap Lead 1",
    "Nordic",         "Hip Aco",        "Mr. Cool",       "Orch Hits",
    "Damp Cat",       "FISHINREEL",     "Melo Trmlo",     "Fois Gras",
    "CheapEP",        "AnaMarcato",     "G Bass",         "Dolphin",
    "Evolve",         "ARRIVAL",        "Wazzo",          "Rap Lead 2",
    "Richard",        "Hip Pick",       "Early Lead",     "BDScrtch",
    "Dukes",          "Mayday MW",      "CoolWAH",        "Mascara",
    "HipWahEP",       "ChorusComp",     "Compton",        "Red Dots",
    "Fragile",        "SpookyVibe",     "Gangsta",        "Rap Lead 3",
    "81Z Comp",       "DarkBass",       "HiPaWheel",      "Rap Scream",
    "InyerBass",      "Pierced",        "Hip Mute",       "Hip Pizz",
    "R&B EP+DX",      "Kustom",         "PortaBass",      "Sirens",
    "Silver",         "Zanaks",         "2001 Sub",       "Sine Lead",
    "UK Oam",         "Fooger",         "D-tune",         "Rap Toyz",
    "Mucus M",        "Future Z",       "FM Guitar",      "Trancedot",
    "Dead?Alive",     "SlowSuckr",      "Clickk",         "KewBrick",
    "Munchkins",      "Ants",           "Snoop Bass",     "BabeMagnet",
    "Jones",          "100 dreams",     "FKitchen",       "Rabino",
    "Teknophobe",     "FizzWah",        "Hip Voice",      "Strobe",
};

// User2 (msb=0x3F lsb=0x09) — copia de fábrica de Preset5 (verificado, sección
// "Nota de fábrica" del documento fuente). Se reutiliza la misma tabla.
#define kUser2 kPreset5

const char* motifProgName(uint8_t msb, uint8_t lsb, uint8_t pc) {
    if (pc > 127) return nullptr;
    if (msb == 0x00 && lsb == 0x00) {
        return kGM[pc];
    }
    if (msb == 0x3F) {
        switch (lsb) {
            case 0: return kPreset1[pc];
            case 1: return kPreset2[pc];
            case 2: return kPreset3[pc];
            case 3: return kPreset4[pc];
            case 4: return kPreset5[pc];
            case 8: return kUser1[pc];
            case 9: return kUser2[pc];
        }
    }
    return nullptr;
}
