// midi/TritonPatches.cpp — Korg Triton (Rack) Program/Combination name table (AITEC 2026-07-04)
// Fuente verificada: docs/Korg_Triton_Patches_Verificado.md
//   - TritonR_VNL_EFGJ1.pdf (Voice Name List oficial, PRELOAD.PCG) — nombres.
//   - TRITON_Rack_MIDIimp.TXT (MIDI Implementation Rev 1.6) — Bank Select MSB/LSB.
// Solo PRELOAD.PCG: INT-A..D (Program+Combination) + Bank G (GM). Sin EXB-x/INT-E/F
// (placas de expansión no instaladas, no aparecen en el VNL de este equipo).
#include "TritonPatches.h"

static const char* const kCombiA[128] = {
    "Romance Layers",    "Lonely Moon",       "DynOrchestra 1",    "Drum'n'Bass Kit",
    "Vocoderhythm",      "[(Goliath )]",      "Ugly Momma D.Kit",  "My Baby's Asleep",
    "Knob as Drawbar1",  "Indian Ocean",      "*Pad Tropolis*",    "Big Jazz Band",
    "Bell Amis",         "Golden Strings",    "Leading Lady",      "Barter Town",
    "Digi SynPiano 1",   "[Ribbon Rappin']",  "Rhythms & Bows",    "Stabbin' Split",
    "Falling Leaves",    "Noisy Funk Synth",  "Drumfest",          "Strumming Guitar",
    "Ballad Organ",      "World Winds",       "Universal Choir",   "The Power Trio",
    "Random Blocks",     "Bows&KnobHarpsi",   "Home Suite Home",   "Meteor Shower",
    "Tiney Harmonic",    "after-T-house",     "Small Orchestra",   "Organic Beats",
    "/\\Gods Bathtub/\\", "Talkin'RaveSynth",  "Arp Session Kit",   "Wavetable Guitar",
    "2nd Harm.on Knob",  "Fisatic Dreams",    "Simple Pad",        "Big Brassed",
    "Angelic Bells",     "CinematicStrings",  "Hidden Rhythm",     "The Rain Forest",
    "Big Bottom Clav",   "Bass & PianoPad",   "French Ensemble",   ": Crusin'Compton:",
    "***Ice*Rain***",    "Spiky & Tight",     "Crazy Hit Tricks",  "Sofia's Place",
    "Upper&Lower Org.",  "Irish Ballade",     "The BeeG Pad",      "MutedButSpeakin'",
    "Bellish Pad",       "AfterRainStrings",  "DreamingForMiles",  "Melanco",
    "ModernPiano",       "Gig Split",         "Woodwinds",         "Steely Keys",
    "**Weightless**",    "BIG Wash Synth",    "Super Hip Kit",     "Harmonic Whisper",
    "Rock Organ",        "Peace On Earth",    "I'm sorry...",      "Sop/Alt/Tnr/Bari",
    "Emtim Bells",       "Smoothie Strings",  "Pad & ShakuLead",   "All Was Lost",
    "EP Stack (Knobs)",  "DanceSynthSplit",   "Bows 'n' Brass",    "DoItToYaFeet (C)",
    "<<SYNERGY>>",       "Cosmic Sweeper",    "SciFi ChaseScene",  "Mountainside",
    "Gospel Church",     "Koto Environment",  "BeeG Pad2 Bright",  "Spittin' Brass",
    "Rotary Bellz",      "Strings Of Silk",   "SweetBabyBlues",    "Jungle Stalker",
    "Comp-o-Net",        "Happily Split",     "Dry Chamber Ens.",  "70's Mirror Ball",
    "Dust Devil",        "Power Synth",       "The16th Strummer",  "New Breed of Gtr",
    "Pipes on SW&Knbs",  "Tropic Of Cancer",  "Please stay calm",  "Warm Brass Ens.",
    "Comfort Bell",      "Sugar Plums",       "Ambient House",     "Alien Invasion",
    "Acoustic Mix",      "5th Synth Split",   "Sweet Dyn-Orch.",   "Prodisynth Split",
    "Planet Pad",        "Square Pad Lead",   "Atmosphere Hit!",   "Guitar Sings",
    "Holy Pipes",        "Gamelan Band",      "**The Toy Box**",   "FunkyBrass Sect.",
    "Little Princess",   "Bowed Strings",     "Life Together",     "One FingerTVShow",
};

static const char* const kCombiB[128] = {
    "Foster Layer EP",   "Phatt Bass Split",  "DynOrchestra 2",    "Formant & Lead",
    "Beat Meditation",   "BIG Power Synth",   "Velo HiFi Kit",     "Alchemy Layer",
    "Jazz Organ 2",      "Prince of Egypt",   "5th.Dimension",     "HybridBrassStab",
    "Cascade Bells",     "ClassicAnaString",  "SimplePad&SopSax",  "{Jealous Robots}",
    "Digi SynPiano 2",   "< The Trio>",       "Orchestra",         "Waterboy Split",
    "Dawn Arp. Pad",     "Mr. Rezzocomp",     "Percfest!!",        "12-Strings (Arp)",
    "Gospel Organ",      "Beyond Nepal...",   "...Water to Wine",  "Trp/Tb/Alto/Tenr",
    "Stereo Mallets",    "Strings & Wings",   "Night Reeds",       "Puff Comper",
    "Dark Bell EP",      "Bass/EP Pad Beat",  "Brash Tpts&Choir",  "Slammin'Bs&Piano",
    "Whopper Pad",       "Ana Logger",        "Mineshaft",         "Magic Guitar",
    "3rd Harm.on Knob",  "Peasant Song",      "Real EP & Pad",     "Dry & Funky Keys",
    "Happy Bells",       "Oct. Strings",      "Warrior Princess",  "Garage Nite",
    "Cutting Clav",      "Jazz Bass/Gtr.",    "Orchestral Brass",  "slow... crawl...",
    "Forget-Me-Not",     "Buzz-A-Log",        "* Instant Euro*",   "Harp Strings",
    "Split ClickOrgan",  "Super Stereo EP",   "<< Godchild >>",    "Fat Horn Section",
    "Pad & Logs",        "Orchestral Pipes",  "Oboe Split",        "Echo Jamm",
    "Wide L/R Piano",    "Bass / Vibe",       "Knob as Drawbar2",  "*HipTrip Split*",
    "Haunted Waters",    "Mutant SoftSynth",  "Snap!ReggaeOrgan",  "Time For Bed",
    "Velo Perc Organ",   "Quidam",            "Hi Key-Beauty-EP",  "Sax Banquet",
    "Vaderian Bells",    "*Arctic Strings*",  "Recorder & Orch.",  "Dirty Beat",
    "Piano Nu-agey",     "Rock Bass/Gtr.",    "Gotham Snd.Track",  "Junga-jam",
    "|| TRANSIT ||",     "Res-Inator",        "[<Moon Jam>]",      "Rock Is King!",
    "Knob as Drawbar3",  "Indian Layers",     "Imaginary PizPad",  "SynBrass Tapper",
    "Mallet Piano",      "LifeSigns EP",      "SplitHornSection",  "Saucy Squares",
    "Synthetic EP's",    "The Sneaky 3",      "Nu Vintage Orch",   "Way Smooth Grv.",
    "Wooshboard",        "Dynamic Change",    "Knob Mixer Kit",    "Arp-A-Listic",
    "Pipes on Knobs",    "Rain Festival",     "Wave Of Time",      "Warm & Horny",
    "Bell and Tine",     "Piano &Strings",    "Riddem & EP",       "Suspected Hit",
    "MegaBrass&Piano",   "Tough to say",      "Pipes&Choir SW",    "Bad Girl Shuffle",
    "The digital sea",   "Digitalian",        "Mr. Trendy",        "Amby Plucked",
    "Soft/Tutti on SW",  "Steel Pan Band",    "Future Japan",      "Wackadoo",
    "Soft Piano Pad",    "Universal Orch.",   "Rock it ship",      "BX-3 Click Organ",
};

static const char* const kCombiC[128] = {
    "Layered A.Piano",   "In The Room",       "Film Tools",        "Invisible Sun",
    "Chromium Pad",      "Huge Ober Sweeps",  "Alien Jungle Jam",  "Encore (High C)",
    "Dirty Drawbars",    "Synthitar Ens.",    "Movie Pad",         "Earth Brass",
    "RandomPanninBelz",  "Lush String Pad",   "Tenor & Pad",       "Millennium Files",
    "Sympathetic EP",    "Bass &Elec.Grand",  "ThickStringBrass",  "Rez Stab Split",
    "Plasma Beings",     "ModulaTech*Synth",  "%%Orgambient%%",    "LastChanceToSee",
    "Jazz Perc (Knob)",  "SlowDance Piano",   "Opera\"Wind Free\"", "Future Brass",
    "Wood+Steel Bars",   "Super Strings",     "Mystic Presence",   "Next Millennium",
    "EP Bell Split",     "Smooth Split",      "DblReeds&Strings",  "The Compin' Man",
    "Inhabited World",   "Analog Punch",      "Speed Racer",       "Warm&Fuzzy Gtr",
    "JazzOrgan/Split",   "VoicyPianoLayer",   "TaiChi Dawn",       "Brass n' Saxes",
    "-Miracle Bells-",   "SmoothOctaveStr",   "Moon's Glow",       "MATRIX",
    "Clav.usFunkus",     "Soft Split-Pad",    "*Warm Orchestra*",  "Velo Bass Stack",
    "Gone Forever",      "Big and Buzzy",     "Stratosphere",      "E.Grand Bell Pad",
    "OrganVel->Brass",   "Highland Tines",    "Triton Voices",     "Muted BigBand",
    "Isle Of Indigo",    "* Epic Cinema *",   "TV Detectv Drive",  "AimForTheMonster",
    "Ballad Layer EP",   "Hybrid Split",      "Piano Concerto",    "Happy Feet !!",
    "Panner-Emma",       "Analog 101",        "Re-Mix-Maven",      "Hybrid Gtr Pad",
    "Vital Organ",       "BellyPianoLayer",   "Good Luck EP Pad",  "Saxobrass",
    "Triple Bell",       "Dirty Robbers",     "Alien Lovers",      "... Zero G's ...",
    "'round the Piano",  "Stab-In-A-Stab",    "Poly Sixual",       "korg@groove.comp",
    "Ice Castle",        "Analog SquareWah",  "Something Wicked",  "Layered M1 Piano",
    "ReggaeAlvinBlues",  "Clicky E.Piano",    "Clean Aire",        "Aggessive Horns",
    "Venus Percs",       "Solo & Ensemble",   "Hold Me... EP",     "TrancenDance",
    "Wurly Dream EP",    "Bumpin'&Thumpin'",  "The Ascension",     "Bad*Street Split",
    "Nebular Motion",    "Soft Blip*Synth",   "\"...MY toys!\"",   "Toro,Toro,Ole!!!",
    "Positive@SW&Knbs",  "World Atmosphere",  "Powerful Throats",  "Warm Low Brass",
    "Bell Animations",   "Burble Swirl",      "E.Pianic Layers",   "Digital Diver",
    "Blaster Keys",      "Square Roots",      "Warm Bars",         "Snowboard Hop",
    "Shh-I'm Sweeping",  "Mir Appears",       "SYNCing Feeling",   "Complex EP Grand",
    "Organ Principle",   "Manhattan Chase",   "Musical Clowns",    "Mustang Saxes",
    "Belle",             "Digimidgets",       "Vacancy...",        "PerihelionSweep",
};

static const char* const kCombiD[128] = {
    "Ballad Grand",      "R&B Lead Split",    "Pompus Brass",      "Mr Happy Arp !",
    "Phases Of Angels",  "Syzzle Synth",      "Sonic FX Mixer",    "The Guitarist",
    "Straight Wheels",   "Marching Pipes",    "Pearly-Gates Gig",  "French Brass",
    "Modern Monastery",  "String Concerto",   "Leading to Peace",  "Alien Translator",
    "GlassyEP&Strings",  "Stationary Split",  "Epic Orchestra",    "Prog Rock Fest",
    "Metamorphoses",     "Ravalogue",         "Carnival Parade",   "Pastoral Guitar",
    "<Standard Bars>",   "Shogun",            "Symphonic Voices",  "Small Sax Ens",
    "Lincoln Logs",      "Violin Sect.",      "Bass-n-Bellz",      "Nunavut Lights",
    "Breathy Bell EP",   "Hot Tub Split",     "Velo Orch Winds",   "The Organ Groove",
    "Respirator",        "TalkBoxBass<Rbn>",  "Cyborg Scratch",    "Rich Guitarist",
    "Jazz Overdrive",    "Accordion (SW) 1",  "*Dying Star*",      "PowrBrassSession",
    "*)BarbieBellz(*",   "3-Octave Strings",  "Splatsburg",        "Deadly Gasses",
    "Village Pump",      "Old Friends",       "Jet Stream",        "RibbonREZ JAM!!",
    "Spheoretical",      "DiscoLivesHERE!!",  "Streetwalk",        "Heaven's Bells",
    "Jazz A Bee",        "October Fest",      "Pulsing 5 Pad",     "Technified",
    "AIRY Bellz",        "SyrupySynthStrs",   "Pad & Knob1 Lead",  "OpenPodBayDoor!",
    "Heaven Layers",     "Titanical Split",   "Dbl. Reed Gang",    "Bass & LFO-er",
    "Northern Stars",    "The Pitz",          "2Hand Beats&Bass",  "*Slinky*",
    "Lovely Old VOX",    "Accordion (SW) 2",  "SecretGroove Pad",  "Techno Fugue",
    "Linear Synthesis",  "Antarctica",        "Electric Pad",      "Don'tLandTheShip",
    "The Key Elements",  "Jungle Split",      "King Cobras",       "Street Cats",
    "Land Of Dreams",    "BellZarra 6/8",     "BIG Gnarly Lead",   "Rhythm Mysters",
    "Glacier Pad",       "African Festival",  "WideOpenSpaces",    "Ghosttown Cornet",
    "ClockmakersDream",  "Serene Strings",    "BigB.Sect.-Split",  "PortaMenthos",
    "The Ballad EP",     "Bass&RezKey<99>",   "Harpsicord Suite",  "Bass & Comp Jam",
    "Juicy Reflection",  "BottlePowerPad",    "Tranquil~Stream~",  "Steam Factory",
    "Grand Procession",  "Svengali Dusk",     "Alpha Mega Synth",  "Smooth DynoBrass",
    "Dreamy*Lillies",    "BellAsian",         "Sweetpad & LEADZ",  "Da Bomb Rap",
    "E. Pierre",         "Fat Analog Split",  "PhunkyWahWahClav",  "Crazy Wah Cafe",
    "Virtual Journey",   "Jazzy BottleLead",  "TalkBoxGtr <Rbn>",  "Mandolin Strums",
    "Sunday Sermon",     "Triton Bay",        "Morning Doves",     "Radiologizer",
    "West Indian Way",   "Orchestr.Strings",  "Any Clock'll Do",   "* User's Slot *",
};

static const char* const kProgA[128] = {
    "Noisy Stabber",     "Acoustic Piano",    "Chipper Dayglow",   "Legato Strings",
    "! {Tricky} Kit !",  "Acoustic Guitar",   "Nasty Bass",        "BX3 Vel Switch",
    "Rez. Down",         "Fat Brass",         "<Techno Vox Box>",  "Fresh Breath",
    "Smooth Sine Lead",  "Sax Ensemble",      "Swirling Dreams",   "Monkey Skulls",
    "Metalic Rez",       "Studio Stage EP",   "Flip Blip",         "Camera Strings",
    "House Kit",         "Chorus E.Guitar",   "Acoustic Bass",     "M1 Organ",
    "Digi Ice Pad",      "Trumpet",           "Sonic Blast",       "Choir of Light",
    "Rezbo",             "TenorSax Growl-Y",  "Tinklin' Pad",      "VS Bell Boy",
    "Power Snap Synth",  "Romance Piano",     "Arp Angeles",       "Arco Strings",
    "Standard Kit",      "Wet Dist. Guitar",  "30303 Mega Bass",   "Dark Jazz-Organ",
    "Clouds of Air",     "SFZ Brass ST",      "Loop-Iteria",       "Oooh Voices ST",
    "HipHop Lead",       "Flute",             "Sinistar*Android",  "Log Drum",
    "Rez. Sweep",        "R&B E.Piano",       "Arp Twins",         "PizzAnsamble",
    "Psycho Kit",        "Vox Wah Chicks",    "SuperSwitch Bass",  "Jazz Organ 1",
    "Ravelian Pad",      "Classic F.Horn",    "Monster Island",    "Aaah Voices ST",
    "Trancer Lead",      "AltoSax2Breath-Y",  "Crimson 5ths",      "Moving Bellz",
    "Ana Brass/Lead",    "90's Piano",        "Wild Arp",          "Stereo Strings",
    "HipHop Kit",        "Jazz Guitar",       "Euro 8va Bass",     "Distortion Organ",
    "Tsunami Waves",     "Glen & The Boys",   "Steam Sweeps",      "White Pad EP",
    "Old & Analog",      "DoubleReed",        "Aqua Phonics",      "Ensemble Bell",
    "Cosmic Furnace",    "Velo Whirly",       "Techno Organ Hit",  "Few Bows Here",
    "Mega Drum Hit",     "Mute Monster",      "Stein Bass",        "Perc Short Decay",
    "Antartic Wind",     "Trombone Hard",     "Orbiting Probes",   "Phantom Of Tine",
    "Seq DDL Lead",      "BariSax Growl -Y",  "Percussive Hits",   "Vibraphone",
    "Digital PolySix",   "Clav",              "Goa Lover",         "AnalogStrings1&2",
    "BD&SD Kit 1",       "Nylon Guitar",      "Jungle Rez Bass",   "Full Drawbars",
    "Money Pad",         "Burnin' Brass",     "VenusianStories",   "SynPiano X",
    "Syncro City",       "Recorder",          "Astral Dreams",     "Bali Gamelon",
    "Super Saw Brass",   "Sweeping EP",       "Jungle Melody",     "WatcherOfTheSky",
    "Orchestra&Ethnic",  "Power-Chords&FX",   "E.Bass Finger",     "Pipe Mixture",
    "{(Meditate})",      "Tight Brass",       "Soundscapes",       "Sitar Sitar",
    "Espress Lead",      "SopranoSax Br.-Y",  "Flying Machines",   "Krystal Bells",
};

static const char* const kProgB[128] = {
    "Synth Sweeper",     "Attack Piano",      "StaccatoPizzHit",   "Octave Strings",
    "Jazz/Brush Kits",   "FingertipsGuitar",  "Dark R&B Bass",     "Old Tone-Wheel",
    "The Pad",           "Brass Expression",  "PiezoMix Guitar",   "Slow Choir ST",
    "Phat Saw Lead",     "Old Shakuhachi",    "OXYGEN",            "Velo Kalimba",
    "Future Syn Pad",    "Dyno Tine EP",      "Brass Impact Hit",  "String Quartet",
    "Processed Kit",     "Vintage Stratt",    "Fretless Bass",     "Tekno Organ*Bass",
    "Brass Pad",         "Muted Trumpet",     "Fisa Americana",    "Vocalesque",
    "Glide Lead",        "TenorSax Brth.-Y",  "Transformation",    "Thin Bell-s-park",
    "Pop Synth Pad",     "Piano Pad",         "Karma Sutra",       "Symphonic Bows",
    "Standard Kit 2",    "Amp D. Guitar",     "30303 Square",      "Sine DWGS-Organ",
    "Simple Sine Pad",   "Octave Brass Exp",  "CyborgFactoryHit",  "E.G. Harmonics",
    "Auto Pilot",        "BambuSilverFlute",  "Dolphin Ride",      "Marimba",
    "Gliding Squares",   "Night Tines EP",    "Mondo'Rimba",       "HybridStrg/Choir",
    "Cymbals Kit",       "Funkin' Guitar",    "Poinker Bass",      "Gospel Organ",
    "HarpsyKorg 8'+4'",  "Horns & Ensemble",  "The Great Wall",    "Full Vox Pad",
    "Musette",           "AltoSax1 Growl-Y",  "E.Bass Pick 1",     "Magical Bells",
    "SynthBrass",        "Classic Piano",     "Big Hit in India",  "Solo Violin",
    "Drum'n'Bass Kit",   "Strato-Chime",      "Digi Syn Bass",     "Classic Click",
    "DJ Touch",          "Big Band Plunger",  "New Voyage",        "Arctic Voices",
    "Goa Message",       "English Horn",      "E.Bass Pick 2",     "Tropico Bells",
    "Mega Big Synth",    "Vintage EP",        "Space Pod for 2",   "Indian Stars",
    "Dragon Gong",       "Feedback D. Gtr.",  "Sweet Fretless",    "Percussion BX3",
    "Dark Night",        "Trombone Ens.",     "Marc Tree",         "Take Voices",
    "Fisa Cassotto",     "Bassoon",           "PedalSteelGuitar",  "Koto",
    "Rezzo Release",     "Sticky Rez Clav",   "Hit Me 2 Times!!",  "Santur",
    "BD&SD Kit 2",       "Old 12-String",     "Ramp Jungle Bass",  "Killer B",
    "L/R Piano(Knob1)",  "Trumpet Ens.",      "MotionSoundTrack",  "Processed E.Gtr.",
    "Fat Syn Sync",      "Spitz Bottle",      "MixFisaMaster 3",   "Future Bell",
    "Flute Pad",         "Hybrid Digi EP",    "Harp",              "Harmonica",
    "Percussion Kit",    "Dynamic E.Guitar",  "Decayed Bass",      "Church Pipes",
    "Digital Bells",     "Classic Fanfare",   "Hemispheres",       "Indian Frets Gtr",
    "Film Brass",        "Jazz Clarinet",     "Pro-Dyno EP",       "Tinkle Bells",
};

static const char* const kProgC[128] = {
    "Techno Phonic",     "Warm E.Grand",      "Rave <Ribbon>",     "Stereo Strings 2",
    "WAcKy HiPHop Kit",  "Spanish Guitar",    "Phat Bass",         "Dirty \"B\"",
    "Super Sweeper",     "DynaBrassStereo1",  "<ReverseVoxBox>",   "Vocalscaping",
    "Sine Switcher",     "Breathy BariSax",   "Stereo WaveSweep",  "Mallet Clocker",
    "PowerRezSweep",     "Pro-Stage EP",      "Motion Raver",      "Rosin Strings",
    "Nasty TRicKy Kit",  "Nu Strat",          "A.Bass Buzzing",    "Perky Tonewheels",
    "DigitalThroats 1",  "Trombone Soft",     "Video Blaster",     "Grand Choir",
    "A leadload",        "Soft TenorSax",     "Cyclic X-Fades",    "Breathy Bells",
    "Auto Groove",       "Piano Pad 2",       "Techno Stat",       "Viola Solo",
    "D'n'B Gate Kit",    "SingleCoil+Piezo",  "SynBassRes",        "Superdark Organ",
    "Goliath's Waves",   "Blind as a Bat",    "Rave Stabz",        "Oooh Choir",
    "X-Mod Raver",       "Breathy AltoSax",   "Spectrum Alloy",    "Log Drum & Bells",
    "Square Rez",        "Dark and Warm",     "Old Record Hit 1",  "Ensemble & Solo",
    "Tiny Perc. Kit",    "CountryNuStrings",  "Slap Bass v/s",     "Jazz Organ 2",
    "Harmonic Pad",      "Tubas Gold",        "Birds & Bugs",      "Aah Choir",
    "Busy Sync",         "Warm Oboe",         "Stereo Rez Sweep",  "GlassBell Bright",
    "Raunchy Brass",     "Piano&String/Pad",  "Old Record Hit 2",  "String World",
    "Gamelan Gong",      "Super Clean Gtr",   "Digi Bass 1",       "Perc-2ndHarmonic",
    "Sweeper Strings",   "BrassSlow Stereo",  "Dirty Wounds",      "Choir Mmh",
    "Sync Kronicity",    "Classic Flute",     "Water is Deep",     "Digital Bells 2",
    "Dual Filterz",      "Classic Wurly",     "Organ Impact",      "Violin & Viola",
    "Psycho Pitch Kit",  "CleanMute-Guitar",  "Fretless Switch",   "BX3 Short Decay",
    "Cross Sweeper",     "Trombones",         "Cosmic Toys",       "DigitalThroats 2",
    "Fire Wave",         "Wooden Flute",      "Smoothy Pad",       "Hybrid Bell",
    "Square Snaps",      "Clav Snap",         "Golithanic Stab",   "ComponentStrings",
    "Jazzy Pitch Kit",   "Fingertips12 Gtr",  "Reso Bass",         "Super BX Perc",
    "Ghostly Strings",   "Attack Brass ST",   "Compu-shift",       "Ooh/Aah VoicesST",
    "Grain Board",       "Bari Blaster",      "JS/Ribbon Pad",     "Ribbon Rhythm",
    "Power Saw",         "Reson Piano",       "Pop Guitar Hit",    "Analog Velvet",
    "KING<>KONG Kit",    "Arpeggio Guitar",   "E.Bass Finger 2",   "Organ Positive",
    "Mellow Movie Pad",  "Movie Brass",       "One Note Stories",  "Ether Voices",
    "Brian's Sync",      "PanFlute",          "Glass Vox",         "Bottle-Bell",
};

static const char* const kProgD[128] = {
    "Ribbon Morpher",    "Super Grand",       "Raggae Gtr Hit",    "PizzicatoSection",
    "UGLY HoUSe Kit",    "Rhythmic E.Gtr",    "Dirty Man Bass",    "Killer BX-3",
    "Ultra Res. Sweep",  "Power Brass",       "Just Do It!!!",     "Dream Voices",
    "Octo Lead",         "Warm Shakuhachi",   "Cinema Pad",        "Kalimba Soft",
    "Thunderlog",        "Club E.Piano",      "Symphonic Waves",   "X-Synced",
    "Tamborine Dream",   "Joystick Gtr(-Y)",  "Fretless Snap",     "Overdrive BX3",
    "That Heaven Vibe",  "DynaBrassStereo2",  "Distant Lights",    "OohSlow VoicesST",
    "Electro Lead",      "WarPipes",          "Pods In The Pad",   "Finger Cymbal",
    "SynthPianoid",      "Chorus Piano",      "Cyber Choir",       "Rich Lead",
    "Djembe/Log Drum",   "Guitarish",         "Hybrid Bass",       "Good Old \"B\"",
    "Analog Pad",        "French Horn Sect",  "Vanishing Planet",  "Classic Vox",
    "BrightPulseLead",   "Digi Layer Keys",   "OutOfTheClouds",    "Garbage Mallets",
    "Band Passed",       "Stereo Digi EP",    "Rhythm Rezonator",  "Syn Pipes",
    "*SpaceShip*",       "Time Machines",     "Thumb Bass",        "Dirty Jazz Organ",
    "Lonley Sphinx",     "The Avenger",       "Bad Weather",       "Cript-on",
    "Thin AnaLead",      "Wacky A.Bass",      "Virtual Traveler",  "Digi-Bell",
    "Cat Lead (-Y)",     "Classic Tines",     "SharpBottleBlow",   "Dance Lead",
    "Piano Layers",      "Filter Gate",       "Digi Bass 2",       "Rotary Organ",
    "Electrik Brass",    "Frozen Glaciers",   "Warm Flugel Horn",  "Wispy Dry Wind",
    "RibbonYoHeadOff!",  "Pipe Tutti",        "Syn Ghostly",       "Warm Steel Drums",
    "Solar Surfing",     "Splat Slap",        "Rhythmnosis",       "The Mandolin",
    "Crazy Wah Wah",     "Square Wave Lead",  "Fretless Bass 2",   "Old VOX Legend",
    "Freedom Pad",       "Classic Digi EP",   "Loonie Bin",        "ResRes One",
    "Unholy Water",      "Shirk Hit",         "Lava Lakes",        "E.Bass Finger 3",
    "Old Portamento",    "Mutant Clav",       "Random Pulsator",   "Mini Lead",
    "DWGS E.Piano",      "Rhythm Of Life",    "SuperSwtch Bass2",  "Full Pipes",
    "Metal SlowPad",     "BeBop Cornet",      "Cosmic Waves",      "Fluttering EP",
    "AMSFeedbackLead",   "Tomorrow's Pad",    "BPM Filter Sweep",  "Small Harp",
    "Dark Element",      "Silky Digi EP",     "Moon Talker",       "Sitar/Tamboura",
    "Rave Volutionary",  "Hubble Pad",        "DynaThumb Bass",    "\"Flauto\" Pipes",
    "Noble Brite Pad",   "Fugue In L.F.O.",   "Black Box",         "Station Of Waves",
    "R&B Lead",          "Motion Ocean !",    "Tight Brass 2",     "Moon Cycles",
};

static const char* const kBankG[128] = {
    "Acoustic Piano",    "Bright Piano",      "El.Grand Piano",    "Honkey-Tonk",
    "Electric Piano 1",  "Electric Piano 2",  "Harpsichord",       "Clavi.",
    "Celesta",           "Glockenspiel",      "Music Box",         "Vibraphone",
    "Marimba",           "Xylophone",         "Tubular Bells",     "Santur",
    "Drawbar Organ 1",   "PercussiveOrgan1",  "Rock Organ",        "Church Organ",
    "Reed Organ",        "Accordion 1",       "Harmonica",         "Bandoneon",
    "Nylon Guitar 1",    "Steel Guitar",      "Jazz Guitar",       "Clean Guitar",
    "Muted Guitar",      "Overdrive Guitar",  "DistortionGuitar",  "Guitar Harmonics",
    "Acoustic Bass",     "Fingered Bass",     "Picked Bass",       "Fretless Bass",
    "Slap Bass 1",       "Slap Bass 2",       "Synth Bass 1",      "Synth Bass 2",
    "Violin",            "Viola",             "Cello",             "Contrabass",
    "Tremolo Strings",   "Pizzicato Str.",    "Orchestral Harp",   "Timpani",
    "Strings",           "Slow Strings",      "Synth Strings 1",   "Synth Strings 2",
    "Choir Aahs 1",      "Voice Oohs",        "Synth Vox",         "Orchestra Hit",
    "Trumpet",           "Trombone 1",        "Tuba",              "Muted Trumpet 1",
    "French Horn",       "Brass Section 1",   "Synth Brass 1",     "Synth Brass 2",
    "Soprano Sax",       "Alto Sax",          "Tenor Sax",         "Baritone Sax",
    "Oboe",              "English Horn",      "Bassoon",           "Clarinet",
    "Piccolo",           "Flute",             "Recorder",          "Pan Flute",
    "Blown Bottle",      "Shakuhachi",        "Whistle",           "Ocarina",
    "Detuned Square",    "Detuned Sawtooth",  "Synth Calliope",    "Chiff Lead",
    "Charang",           "Air Voice",         "5th Sawtooth",      "Bass & Lead",
    "Fantasia",          "Warm Pad",          "Polyphonic Synth",  "Space Voice",
    "Bowed Glass",       "Metallic Pad",      "Halo Pad",          "Sweep Pad",
    "Ice Rain",          "Sound Track",       "Crystal",           "Atmosphere",
    "Brightness",        "Goblins",           "Echo Drops",        "Star Theme",
    "Sitar 1",           "Banjo",             "Shamisen",          "Koto",
    "Kalimba",           "Bagpipe",           "Fiddle",            "Shanai",
    "Tinkle Bell",       "Agogo",             "Steel Drums",       "Woodblock",
    "Taiko",             "Melodic Tom 1",     "Synth Drum",        "Reverse Cymbal",
    "Gtr.Fret Noise",    "Breath Noise",      "Seashore",          "Bird Tweet 1",
    "Telephone Ring 1",  "Helicopter",        "Applause",          "Gun Shot",
};

const char* tritonProgName(uint8_t msb, uint8_t lsb, uint8_t pc) {
    if (pc > 127) return nullptr;
    if (msb == 0x00) {
        switch (lsb) {
            case 0: return kProgA[pc];
            case 1: return kProgB[pc];
            case 2: return kProgC[pc];
            case 3: return kProgD[pc];
        }
    } else if (msb == 0x79 && lsb == 0x00) {
        return kBankG[pc];
    }
    return nullptr;
}

const char* tritonCombiName(uint8_t msb, uint8_t lsb, uint8_t pc) {
    if (pc > 127) return nullptr;
    if (msb == 0x00) {
        switch (lsb) {
            case 0: return kCombiA[pc];
            case 1: return kCombiB[pc];
            case 2: return kCombiC[pc];
            case 3: return kCombiD[pc];
        }
    }
    return nullptr;
}
